change analysis test suite to not take the expectation into account anymore

diff --git a/run_analysis_tests b/run_analysis_tests
--- a/run_analysis_tests
+++ b/run_analysis_tests
@@ -52,52 +52,57 @@ function addResultSummary() {
     local pattern=""
 
     if [[ "$resultFile" == *"analysis-fails"* ]]; then
-        suffix="PASSED"
-
-        while read line; do
-            if echo "$line" | grep -q "^//"; then
-                pattern=`echo "$line" | sed 's/^[/]*//'`
-                echo $pattern | grep -q "^\^"
-                negate=$?
-                echo $pattern | grep -q "^#"
-                count=$?
-                if [[ $negate == 0 ]]; then
-                    summary="$summary\n\nError must not be shown: ${pattern:1}"
-                    if grep -qi "${pattern:1}" "analysis-results/$resultFile.txt"; then
-                        summary="$summary\nTEST DID NOT PASS: The error was present in analysis:"
-                        errorInFile=$(grep -i "${pattern:1}" "analysis-results/$resultFile.txt")
-                        summary="$summary\n\t$errorInFile"
-                        suffix="FAILED"
-                    else
-                        summary="$summary\nTEST PASSED: Error was not present in analysis"
-                    fi
-                elif [[ $count == 0 ]]; then
-                    occurrences=`echo $pattern | perl -pe 's/^#([0-9]+) .*$/\1/'`
-                    pattern=`echo $pattern | perl -pe 's/^#[0-9]+ (.*)$/\1/'`
-                    summary="$summary\n\nError must be shown $occurrences times: $pattern"
-                    foundlines=`grep -i "$pattern" "analysis-results/$resultFile.txt" | wc -l`
-                    summary="$summary\nError was found $foundlines times"
-                    if [ $foundlines -ne $occurrences ]; then
-                        summary="$summary\nTEST DID NOT PASS"
-                        suffix="FAILED"
-                    else
-                        summary="$summary\nTEST PASSED"
-                    fi
-                else
-                    summary="$summary\n\nError must be shown: $pattern"
-                    if ! grep -qi "$pattern" "analysis-results/$resultFile.txt"; then
-                        summary="$summary\nTEST FAILED: Error was not present in analysis"
-                        suffix="FAILED"
-                    else
-                        errorInFile=$(grep -i "$pattern" "analysis-results/$resultFile.txt")
-                        summary="$summary\nTEST PASSED: Error was present in analysis:"
-                        summary="$summary\n\t$errorInFile"
-                    fi
-                fi
-            else
-                break
-            fi
-        done <"$testFile"
+        if [ ! "$errors" -eq "0" ]; then
+            suffix="PASSED"
+        else
+            suffix="FAILED"
+        fi
+#         suffix="PASSED"
+# 
+#         while read line; do
+#             if echo "$line" | grep -q "^//"; then
+#                 pattern=`echo "$line" | sed 's/^[/]*//'`
+#                 echo $pattern | grep -q "^\^"
+#                 negate=$?
+#                 echo $pattern | grep -q "^#"
+#                 count=$?
+#                 if [[ $negate == 0 ]]; then
+#                     summary="$summary\n\nError must not be shown: ${pattern:1}"
+#                     if grep -qi "${pattern:1}" "analysis-results/$resultFile.txt"; then
+#                         summary="$summary\nTEST DID NOT PASS: The error was present in analysis:"
+#                         errorInFile=$(grep -i "${pattern:1}" "analysis-results/$resultFile.txt")
+#                         summary="$summary\n\t$errorInFile"
+#                         suffix="FAILED"
+#                     else
+#                         summary="$summary\nTEST PASSED: Error was not present in analysis"
+#                     fi
+#                 elif [[ $count == 0 ]]; then
+#                     occurrences=`echo $pattern | perl -pe 's/^#([0-9]+) .*$/\1/'`
+#                     pattern=`echo $pattern | perl -pe 's/^#[0-9]+ (.*)$/\1/'`
+#                     summary="$summary\n\nError must be shown $occurrences times: $pattern"
+#                     foundlines=`grep -i "$pattern" "analysis-results/$resultFile.txt" | wc -l`
+#                     summary="$summary\nError was found $foundlines times"
+#                     if [ $foundlines -ne $occurrences ]; then
+#                         summary="$summary\nTEST DID NOT PASS"
+#                         suffix="FAILED"
+#                     else
+#                         summary="$summary\nTEST PASSED"
+#                     fi
+#                 else
+#                     summary="$summary\n\nError must be shown: $pattern"
+#                     if ! grep -qi "$pattern" "analysis-results/$resultFile.txt"; then
+#                         summary="$summary\nTEST FAILED: Error was not present in analysis"
+#                         suffix="FAILED"
+#                     else
+#                         errorInFile=$(grep -i "$pattern" "analysis-results/$resultFile.txt")
+#                         summary="$summary\nTEST PASSED: Error was present in analysis:"
+#                         summary="$summary\n\t$errorInFile"
+#                     fi
+#                 fi
+#             else
+#                 break
+#             fi
+#         done <"$testFile"
     fi
 
     if [[ "$resultFile" == *"analysis-succeeds"* ]]; then
